version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    volumes:
      - ./backend:/app
      - sqlite_data:/app/db  # Persist SQLite database
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=zreo_interviewai.settings
      # Remove PostgreSQL related environment variables
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  sqlite_data:  # For persisting the SQLite database file