services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data  # for persistent sqlite database
      - media_files:/app/media  # Add this line
      - frontend_build:/app/dist 
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,nginx

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.prod
    environment:
      - NODE_ENV=production
    volumes:
      - build_files:/app/dist

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    
    volumes:
      - build_files:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  build_files:
  sqlite_data:  # volume for sqlite database
  media_files: 
  frontend_build: