services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
      - media_files:/app/media
      - frontend_build:/app/dist 
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,nginx
    networks:
      - app-network
    expose:
      - 8000

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.prod
    volumes:
      - build_files:/app/dist
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://nginx

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - build_files:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  build_files:
  sqlite_data:
  media_files:
  frontend_build: