# render.yaml (for production on Render.com)
services:
  - type: web
    name: your-app
    env: python
    buildCommand: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      
      # Build frontend
      cd frontend
      npm install
      npm run build
      
      # Install Python dependencies
      cd ../backend
      pip install -r requirements.txt
      
      # Collect static files
      python manage.py collectstatic --noinput
    startCommand: |
      cd backend
      python manage.py migrate
      gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: NODE_VERSION
        value: 18.0.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"