services:
  - name: frontend
    type: web
    env: docker
    dockerfilePath: docker/frontend.Dockerfile
    envVars:
      - key: NODE_ENV
        value: development
    disk: # Define a persistent disk if needed
      name: frontend_disk
      mountPath: /app
      sizeGB: 1 # Adjust as needed

  - name: backend
    type: web
    env: docker
    dockerfilePath: docker/backend.Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zreo_interviewai.settings
    disk: # For persisting the SQLite database file
      name: sqlite_data
      mountPath: /app/db
      sizeGB: 1  # Adjust size based on your data needs

envVarGroups: # Use if you have multiple common environment variables
  - name: my-app-settings
    envVars:
      - key: COMMON_SETTING
        value: example_value

